### PR TITLE
Fixed namespace

### PR DESCRIPTION
**Pull request by alessiobianchini**
Fixed wrong namespace in PointOfSale project

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]
Oops! Thank you!

**Comment by jfversluis** [comment]
Looks like the linked converter needs to be updated too: https://github.com/dotnet/maui-samples/blob/main/8.0/Apps/PointOfSale/src/PointOfSale/Converters/CheckedColorConverter.cs#L3

**Comment by jfversluis** [comment]
@alessiobianchini no worries! If you could just make the cla bot happy with that little comment I hope it will be all good now!

**Comment by alessiobianchini** [comment]
@dotnet-policy-service agree [company="DOIT srl"]

**Comment by alessiobianchini** [comment]
@dotnet-policy-service agree company="DOIT srl"

**Review by jfversluis — APPROVED** [review]
Looks like the build pipeline needs an update which is unrelated to this. Thanks for making the samples better!

**Pull request merged**
