### PR TITLE
BugSweeper

### LINKED ISSUE #445: BugSweeper
Port BugSweeper from Xamarin.Forms to .NET MAUI.

---
[Associated WorkItem - 216253](https://dev.azure.com/msft-skilling/Content/_workitems/edit/216253)

### PR DESCRIPTION
**Pull request by davidbritch**
Fixes #445

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by arseniigorkin** [comment]
Hi! It cannot be run/built as it uses MAUI Controls 8.0.7 which makes unknown conflicts with something and makes MauiUIApplicationDelegate not found.

**Comment by jfversluis** [comment]
Looks like you might be hitting this: https://github.com/dotnet/maui/issues/20847

**Comment by arseniigorkin** [comment]
> Looks like you might be hitting this: [dotnet/maui#20847](https://github.com/dotnet/maui/issues/20847)

Hi! Are you able to build the game without the issue with this?
Thx.

**Comment by jfversluis** [comment]
We build all of our samples in an automated pipeline as part of adding them to this repository. You can see the summary of that here: https://github.com/dotnet/maui-samples/actions/runs/8066602046.

So yes, this is able to build

**Comment by davidbritch** [comment]
Hi @arseniigorkin 

The issue is this: there's an `AbsoluteLayout` bug on Android that's only fixed in 8.0.7. So you can use previous MAUI releases on the other platforms and the sample is fine on those platforms. But for the sample to work on Android you need 8.0.7.

Even with 8.0.7 the sample should build fine in VS, provided that your workloads have been 100% managed by VS (meaning you've never use the .NET CLI to install your workloads). It's on a Mac that you can encounter issues building the sample. In that case remove the `<MauiVersion />` line from the .csproj and it *should* build (but there'll be a layout bug on Android then).

**Pull request merged**
