### PR TITLE
Enhanced BeginnersSeries sample (MauiApp2) to be more beginner's friendly

### PR DESCRIPTION
**Pull request by tscholze**
**Motivation**
I'm currently learning and playing around with .NET MAUI. I really like the samples in this repository.

In my eyes as an absolute beginner, the code could be a little bit enhanced to be more friendly for first-timers in the MAUI ecosystem.

Besides this, I renamed sample to avoid generic `MauiApp2` and be more aligned with other samples in its naming.

**Changes**
- Updated solution, project and namespace to 'BeginnersTask' to be aligned with other samples naming structure
- Fixed missing indents
- Added comment to `MauiProgram.cs` with helpful links to Microsoft Learn
- Added comment to `MainViewModel.cs` with helpful code pointers to see related setups and receivers of routings

### CODE REVIEW

**Comment by tscholze** [comment]
@microsoft-github-policy-service agree

**Comment by tscholze** [comment]
@microsoft-github-policy-service rerun

**Comment by jfversluis** [comment]
@microsoft-github-policy-service rerun

**Comment by tscholze** [comment]
@dotnet-policy-service agree

**Review by davidbritch — APPROVED** [review]
Many thanks @tscholze

**Comment by tscholze** [comment]
You are welcome @davidbritch - thanks for accepting such minor changes - it feels awesome!

**Pull request merged**
