### PR TITLE
add maui-preview in nuget.config

### PR DESCRIPTION
**Pull request by infofromca**

### CODE REVIEW

**Review by jonathanpeppers — CHANGES_REQUESTED** [review]
Our goal is to no longer have a NuGet.config file in these samples. Can you explain a bit more on what you’re trying to do here? We can maybe do something on the develop branch for this, but not main.

**Comment by infofromca** [comment]
> Our goal is to no longer have a NuGet.config file in these samples. Can you explain a bit more on what you’re trying to do here? We can maybe do something on the develop branch for this, but not main.

if we do not have this, the project cannot pass the build. ---around 10 Red Errors

**Comment by jonathanpeppers** [comment]
@infofromca can you share a build log? What are the errors?

If you do `dotnet build -bl`, it will create a `msbuild.binlog` file you should be able to zip and share here. Thanks!

**Comment by infofromca** [comment]
the other guy got the same as mine.
fix https://github.com/dotnet/maui/issues/1114

**Comment by infofromca** [comment]
to avoid it, I think it is better to add  nuget lib  inside the project

**Comment by jonathanpeppers** [comment]
> to avoid it, I think it is better to add nuget lib inside the project

Nope, we need to understand what is _actually missing_, so it can be pushed to NuGet.org.

**Comment by jonathanpeppers** [comment]
Things changed a lot in Preview 6. .NET MAUI is now a "workload" and not a NuGet package anymore.

Can you test and see if you're running into this issue still? Thanks!

**Pull request closed without merging**
